# Generated by Django 3.2.3 on 2021-06-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticism',
            name='criticism_set',
        ),
    ]
