# Generated by Django 3.2.3 on 2021-06-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_criticism_criticism_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='geners',
            new_name='genres',
        ),
    ]
